FROM golang:1.25.4-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o l7-proxy ./cmd/proxy

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/l7-proxy .
COPY config.yaml .
EXPOSE 8080 8081
CMD ["./l7-proxy"]